package cn.com.yuyang.pojo;

import java.util.Date;

public class Bumen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.buMenMingCheng
     *
     * @mbg.generated
     */
    private String bumenmingcheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.buMenJianJie
     *
     * @mbg.generated
     */
    private String bumenjianjie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.dangAnId
     *
     * @mbg.generated
     */
    private Integer danganid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.chuangJianShiJian
     *
     * @mbg.generated
     */
    private Date chuangjianshijian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.id
     *
     * @return the value of bumen.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.id
     *
     * @param id the value for bumen.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.buMenMingCheng
     *
     * @return the value of bumen.buMenMingCheng
     *
     * @mbg.generated
     */
    public String getBumenmingcheng() {
        return bumenmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.buMenMingCheng
     *
     * @param bumenmingcheng the value for bumen.buMenMingCheng
     *
     * @mbg.generated
     */
    public void setBumenmingcheng(String bumenmingcheng) {
        this.bumenmingcheng = bumenmingcheng == null ? null : bumenmingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.buMenJianJie
     *
     * @return the value of bumen.buMenJianJie
     *
     * @mbg.generated
     */
    public String getBumenjianjie() {
        return bumenjianjie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.buMenJianJie
     *
     * @param bumenjianjie the value for bumen.buMenJianJie
     *
     * @mbg.generated
     */
    public void setBumenjianjie(String bumenjianjie) {
        this.bumenjianjie = bumenjianjie == null ? null : bumenjianjie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.dangAnId
     *
     * @return the value of bumen.dangAnId
     *
     * @mbg.generated
     */
    public Integer getDanganid() {
        return danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.dangAnId
     *
     * @param danganid the value for bumen.dangAnId
     *
     * @mbg.generated
     */
    public void setDanganid(Integer danganid) {
        this.danganid = danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.chuangJianShiJian
     *
     * @return the value of bumen.chuangJianShiJian
     *
     * @mbg.generated
     */
    public Date getChuangjianshijian() {
        return chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.chuangJianShiJian
     *
     * @param chuangjianshijian the value for bumen.chuangJianShiJian
     *
     * @mbg.generated
     */
    public void setChuangjianshijian(Date chuangjianshijian) {
        this.chuangjianshijian = chuangjianshijian;
    }
}