package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Bumen;

public interface BumenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int insert(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int insertSelective(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    Bumen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bumen record);
}