package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Denglu;

public interface DengluMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table denglu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table denglu
     *
     * @mbg.generated
     */
    int insert(Denglu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table denglu
     *
     * @mbg.generated
     */
    int insertSelective(Denglu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table denglu
     *
     * @mbg.generated
     */
    Denglu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table denglu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Denglu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table denglu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Denglu record);
}