package cn.com.yuyang.pojo;

import java.util.Date;

public class Denglu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.dangAnId
     *
     * @mbg.generated
     */
    private Integer danganid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.miMa
     *
     * @mbg.generated
     */
    private String mima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.dengLuCiShu
     *
     * @mbg.generated
     */
    private Integer denglucishu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.zuiHouYiCiDengLuShiJian
     *
     * @mbg.generated
     */
    private Date zuihouyicidenglushijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.cuoWuCiShu
     *
     * @mbg.generated
     */
    private Integer cuowucishu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.dongJieShiJian
     *
     * @mbg.generated
     */
    private Date dongjieshijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.zhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.gongHao
     *
     * @mbg.generated
     */
    private String gonghao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.shouJiHaoMa
     *
     * @mbg.generated
     */
    private String shoujihaoma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column denglu.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.id
     *
     * @return the value of denglu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.id
     *
     * @param id the value for denglu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.dangAnId
     *
     * @return the value of denglu.dangAnId
     *
     * @mbg.generated
     */
    public Integer getDanganid() {
        return danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.dangAnId
     *
     * @param danganid the value for denglu.dangAnId
     *
     * @mbg.generated
     */
    public void setDanganid(Integer danganid) {
        this.danganid = danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.miMa
     *
     * @return the value of denglu.miMa
     *
     * @mbg.generated
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.miMa
     *
     * @param mima the value for denglu.miMa
     *
     * @mbg.generated
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.dengLuCiShu
     *
     * @return the value of denglu.dengLuCiShu
     *
     * @mbg.generated
     */
    public Integer getDenglucishu() {
        return denglucishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.dengLuCiShu
     *
     * @param denglucishu the value for denglu.dengLuCiShu
     *
     * @mbg.generated
     */
    public void setDenglucishu(Integer denglucishu) {
        this.denglucishu = denglucishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.zuiHouYiCiDengLuShiJian
     *
     * @return the value of denglu.zuiHouYiCiDengLuShiJian
     *
     * @mbg.generated
     */
    public Date getZuihouyicidenglushijian() {
        return zuihouyicidenglushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.zuiHouYiCiDengLuShiJian
     *
     * @param zuihouyicidenglushijian the value for denglu.zuiHouYiCiDengLuShiJian
     *
     * @mbg.generated
     */
    public void setZuihouyicidenglushijian(Date zuihouyicidenglushijian) {
        this.zuihouyicidenglushijian = zuihouyicidenglushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.cuoWuCiShu
     *
     * @return the value of denglu.cuoWuCiShu
     *
     * @mbg.generated
     */
    public Integer getCuowucishu() {
        return cuowucishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.cuoWuCiShu
     *
     * @param cuowucishu the value for denglu.cuoWuCiShu
     *
     * @mbg.generated
     */
    public void setCuowucishu(Integer cuowucishu) {
        this.cuowucishu = cuowucishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.dongJieShiJian
     *
     * @return the value of denglu.dongJieShiJian
     *
     * @mbg.generated
     */
    public Date getDongjieshijian() {
        return dongjieshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.dongJieShiJian
     *
     * @param dongjieshijian the value for denglu.dongJieShiJian
     *
     * @mbg.generated
     */
    public void setDongjieshijian(Date dongjieshijian) {
        this.dongjieshijian = dongjieshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.zhuangTai
     *
     * @return the value of denglu.zhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.zhuangTai
     *
     * @param zhuangtai the value for denglu.zhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.gongHao
     *
     * @return the value of denglu.gongHao
     *
     * @mbg.generated
     */
    public String getGonghao() {
        return gonghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.gongHao
     *
     * @param gonghao the value for denglu.gongHao
     *
     * @mbg.generated
     */
    public void setGonghao(String gonghao) {
        this.gonghao = gonghao == null ? null : gonghao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.shouJiHaoMa
     *
     * @return the value of denglu.shouJiHaoMa
     *
     * @mbg.generated
     */
    public String getShoujihaoma() {
        return shoujihaoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.shouJiHaoMa
     *
     * @param shoujihaoma the value for denglu.shouJiHaoMa
     *
     * @mbg.generated
     */
    public void setShoujihaoma(String shoujihaoma) {
        this.shoujihaoma = shoujihaoma == null ? null : shoujihaoma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column denglu.token
     *
     * @return the value of denglu.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column denglu.token
     *
     * @param token the value for denglu.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}