package cn.com.yuyang.pojo;

import cn.com.yuyang.bean.GongGaoBean;
import cn.com.yuyang.pojo.Gongzuojilu;

import java.util.List;

public interface GongzuojiluMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzuojilu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzuojilu
     *
     * @mbg.generated
     */
    int insert(Gongzuojilu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzuojilu
     *
     * @mbg.generated
     */
    int insertSelective(Gongzuojilu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzuojilu
     *
     * @mbg.generated
     */
    Gongzuojilu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzuojilu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gongzuojilu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzuojilu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gongzuojilu record);


    int countRiZhi(GongGaoBean gongGaoBean);
}