package cn.com.yuyang.pojo;

public interface GonggaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    int insert(Gonggao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    int insertSelective(Gonggao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    Gonggao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gonggao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Gonggao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gonggao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gonggao record);
}