package cn.com.yuyang.pojo;

import java.util.Date;

public class Gonggao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.dangAnId
     *
     * @mbg.generated
     */
    private Integer danganid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.gongGaoMingCheng
     *
     * @mbg.generated
     */
    private String gonggaomingcheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.faBuShiJian
     *
     * @mbg.generated
     */
    private Date fabushijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.lanMu
     *
     * @mbg.generated
     */
    private String lanmu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.fuJianDiZhi
     *
     * @mbg.generated
     */
    private String fujiandizhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.buMenId
     *
     * @mbg.generated
     */
    private Integer bumenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.liuLanShu
     *
     * @mbg.generated
     */
    private Integer liulanshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.zhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gonggao.neiRong
     *
     * @mbg.generated
     */
    private String neirong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.id
     *
     * @return the value of gonggao.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.id
     *
     * @param id the value for gonggao.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.dangAnId
     *
     * @return the value of gonggao.dangAnId
     *
     * @mbg.generated
     */
    public Integer getDanganid() {
        return danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.dangAnId
     *
     * @param danganid the value for gonggao.dangAnId
     *
     * @mbg.generated
     */
    public void setDanganid(Integer danganid) {
        this.danganid = danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.gongGaoMingCheng
     *
     * @return the value of gonggao.gongGaoMingCheng
     *
     * @mbg.generated
     */
    public String getGonggaomingcheng() {
        return gonggaomingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.gongGaoMingCheng
     *
     * @param gonggaomingcheng the value for gonggao.gongGaoMingCheng
     *
     * @mbg.generated
     */
    public void setGonggaomingcheng(String gonggaomingcheng) {
        this.gonggaomingcheng = gonggaomingcheng == null ? null : gonggaomingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.faBuShiJian
     *
     * @return the value of gonggao.faBuShiJian
     *
     * @mbg.generated
     */
    public Date getFabushijian() {
        return fabushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.faBuShiJian
     *
     * @param fabushijian the value for gonggao.faBuShiJian
     *
     * @mbg.generated
     */
    public void setFabushijian(Date fabushijian) {
        this.fabushijian = fabushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.lanMu
     *
     * @return the value of gonggao.lanMu
     *
     * @mbg.generated
     */
    public String getLanmu() {
        return lanmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.lanMu
     *
     * @param lanmu the value for gonggao.lanMu
     *
     * @mbg.generated
     */
    public void setLanmu(String lanmu) {
        this.lanmu = lanmu == null ? null : lanmu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.fuJianDiZhi
     *
     * @return the value of gonggao.fuJianDiZhi
     *
     * @mbg.generated
     */
    public String getFujiandizhi() {
        return fujiandizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.fuJianDiZhi
     *
     * @param fujiandizhi the value for gonggao.fuJianDiZhi
     *
     * @mbg.generated
     */
    public void setFujiandizhi(String fujiandizhi) {
        this.fujiandizhi = fujiandizhi == null ? null : fujiandizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.buMenId
     *
     * @return the value of gonggao.buMenId
     *
     * @mbg.generated
     */
    public Integer getBumenid() {
        return bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.buMenId
     *
     * @param bumenid the value for gonggao.buMenId
     *
     * @mbg.generated
     */
    public void setBumenid(Integer bumenid) {
        this.bumenid = bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.liuLanShu
     *
     * @return the value of gonggao.liuLanShu
     *
     * @mbg.generated
     */
    public Integer getLiulanshu() {
        return liulanshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.liuLanShu
     *
     * @param liulanshu the value for gonggao.liuLanShu
     *
     * @mbg.generated
     */
    public void setLiulanshu(Integer liulanshu) {
        this.liulanshu = liulanshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.zhuangTai
     *
     * @return the value of gonggao.zhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.zhuangTai
     *
     * @param zhuangtai the value for gonggao.zhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gonggao.neiRong
     *
     * @return the value of gonggao.neiRong
     *
     * @mbg.generated
     */
    public String getNeirong() {
        return neirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gonggao.neiRong
     *
     * @param neirong the value for gonggao.neiRong
     *
     * @mbg.generated
     */
    public void setNeirong(String neirong) {
        this.neirong = neirong == null ? null : neirong.trim();
    }
}