package cn.com.yuyang.pojo;

import java.util.Date;

public class Gongzuojilu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzuojilu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzuojilu.leiXing
     *
     * @mbg.generated
     */
    private String leixing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzuojilu.shiJian
     *
     * @mbg.generated
     */
    private Date shijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzuojilu.dangAnId
     *
     * @mbg.generated
     */
    private Integer danganid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzuojilu.zhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzuojilu.jieShouRenId
     *
     * @mbg.generated
     */
    private Integer jieshourenid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzuojilu.id
     *
     * @return the value of gongzuojilu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzuojilu.id
     *
     * @param id the value for gongzuojilu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzuojilu.leiXing
     *
     * @return the value of gongzuojilu.leiXing
     *
     * @mbg.generated
     */
    public String getLeixing() {
        return leixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzuojilu.leiXing
     *
     * @param leixing the value for gongzuojilu.leiXing
     *
     * @mbg.generated
     */
    public void setLeixing(String leixing) {
        this.leixing = leixing == null ? null : leixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzuojilu.shiJian
     *
     * @return the value of gongzuojilu.shiJian
     *
     * @mbg.generated
     */
    public Date getShijian() {
        return shijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzuojilu.shiJian
     *
     * @param shijian the value for gongzuojilu.shiJian
     *
     * @mbg.generated
     */
    public void setShijian(Date shijian) {
        this.shijian = shijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzuojilu.dangAnId
     *
     * @return the value of gongzuojilu.dangAnId
     *
     * @mbg.generated
     */
    public Integer getDanganid() {
        return danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzuojilu.dangAnId
     *
     * @param danganid the value for gongzuojilu.dangAnId
     *
     * @mbg.generated
     */
    public void setDanganid(Integer danganid) {
        this.danganid = danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzuojilu.zhuangTai
     *
     * @return the value of gongzuojilu.zhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzuojilu.zhuangTai
     *
     * @param zhuangtai the value for gongzuojilu.zhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzuojilu.jieShouRenId
     *
     * @return the value of gongzuojilu.jieShouRenId
     *
     * @mbg.generated
     */
    public Integer getJieshourenid() {
        return jieshourenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzuojilu.jieShouRenId
     *
     * @param jieshourenid the value for gongzuojilu.jieShouRenId
     *
     * @mbg.generated
     */
    public void setJieshourenid(Integer jieshourenid) {
        this.jieshourenid = jieshourenid;
    }
}