package cn.com.yuyang.pojo;

public interface HaoyoubiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haoyoubiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haoyoubiao
     *
     * @mbg.generated
     */
    int insert(Haoyoubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haoyoubiao
     *
     * @mbg.generated
     */
    int insertSelective(Haoyoubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haoyoubiao
     *
     * @mbg.generated
     */
    Haoyoubiao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haoyoubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Haoyoubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haoyoubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Haoyoubiao record);
}