package cn.com.yuyang.pojo;

public class Haoyoubiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoyoubiao.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoyoubiao.benRenId
     *
     * @mbg.generated
     */
    private Integer benrenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoyoubiao.haoYouId
     *
     * @mbg.generated
     */
    private Integer haoyouid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoyoubiao.id
     *
     * @return the value of haoyoubiao.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoyoubiao.id
     *
     * @param id the value for haoyoubiao.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoyoubiao.benRenId
     *
     * @return the value of haoyoubiao.benRenId
     *
     * @mbg.generated
     */
    public Integer getBenrenid() {
        return benrenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoyoubiao.benRenId
     *
     * @param benrenid the value for haoyoubiao.benRenId
     *
     * @mbg.generated
     */
    public void setBenrenid(Integer benrenid) {
        this.benrenid = benrenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoyoubiao.haoYouId
     *
     * @return the value of haoyoubiao.haoYouId
     *
     * @mbg.generated
     */
    public Integer getHaoyouid() {
        return haoyouid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoyoubiao.haoYouId
     *
     * @param haoyouid the value for haoyoubiao.haoYouId
     *
     * @mbg.generated
     */
    public void setHaoyouid(Integer haoyouid) {
        this.haoyouid = haoyouid;
    }
}