package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Kaoqin;

public interface KaoqinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbg.generated
     */
    int insert(Kaoqin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbg.generated
     */
    int insertSelective(Kaoqin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbg.generated
     */
    Kaoqin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Kaoqin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Kaoqin record);
}