package cn.com.yuyang.pojo;

import java.util.Date;

public class Kaoqin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.dangAnId
     *
     * @mbg.generated
     */
    private Integer danganid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.shangWuShangBan
     *
     * @mbg.generated
     */
    private Date shangwushangban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.xiaWuXiaBan
     *
     * @mbg.generated
     */
    private Date xiawuxiaban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.zhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.qingJiaZhuangTai
     *
     * @mbg.generated
     */
    private String qingjiazhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.dangTianRiQi
     *
     * @mbg.generated
     */
    private Date dangtianriqi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.id
     *
     * @return the value of kaoqin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.id
     *
     * @param id the value for kaoqin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.dangAnId
     *
     * @return the value of kaoqin.dangAnId
     *
     * @mbg.generated
     */
    public Integer getDanganid() {
        return danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.dangAnId
     *
     * @param danganid the value for kaoqin.dangAnId
     *
     * @mbg.generated
     */
    public void setDanganid(Integer danganid) {
        this.danganid = danganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.shangWuShangBan
     *
     * @return the value of kaoqin.shangWuShangBan
     *
     * @mbg.generated
     */
    public Date getShangwushangban() {
        return shangwushangban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.shangWuShangBan
     *
     * @param shangwushangban the value for kaoqin.shangWuShangBan
     *
     * @mbg.generated
     */
    public void setShangwushangban(Date shangwushangban) {
        this.shangwushangban = shangwushangban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.xiaWuXiaBan
     *
     * @return the value of kaoqin.xiaWuXiaBan
     *
     * @mbg.generated
     */
    public Date getXiawuxiaban() {
        return xiawuxiaban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.xiaWuXiaBan
     *
     * @param xiawuxiaban the value for kaoqin.xiaWuXiaBan
     *
     * @mbg.generated
     */
    public void setXiawuxiaban(Date xiawuxiaban) {
        this.xiawuxiaban = xiawuxiaban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.zhuangTai
     *
     * @return the value of kaoqin.zhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.zhuangTai
     *
     * @param zhuangtai the value for kaoqin.zhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.qingJiaZhuangTai
     *
     * @return the value of kaoqin.qingJiaZhuangTai
     *
     * @mbg.generated
     */
    public String getQingjiazhuangtai() {
        return qingjiazhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.qingJiaZhuangTai
     *
     * @param qingjiazhuangtai the value for kaoqin.qingJiaZhuangTai
     *
     * @mbg.generated
     */
    public void setQingjiazhuangtai(String qingjiazhuangtai) {
        this.qingjiazhuangtai = qingjiazhuangtai == null ? null : qingjiazhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.dangTianRiQi
     *
     * @return the value of kaoqin.dangTianRiQi
     *
     * @mbg.generated
     */
    public Date getDangtianriqi() {
        return dangtianriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.dangTianRiQi
     *
     * @param dangtianriqi the value for kaoqin.dangTianRiQi
     *
     * @mbg.generated
     */
    public void setDangtianriqi(Date dangtianriqi) {
        this.dangtianriqi = dangtianriqi;
    }
}