package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Qingjiabiao;

public interface QingjiabiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int insert(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int insertSelective(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    Qingjiabiao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Qingjiabiao record);
}