package cn.com.yuyang.pojo;

import cn.com.yuyang.bean.GongGaoBean;
import cn.com.yuyang.bean.ShouYeBean;
import cn.com.yuyang.pojo.Qingjiabiao;

public interface QingjiabiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int insert(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int insertSelective(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    Qingjiabiao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Qingjiabiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qingjiabiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Qingjiabiao record);


    /**
     *
     * 根据人员ID查询为处理的请假消息为几条
     * @param gongGaoBean
     * @return
     */
     int  countQingJia(GongGaoBean gongGaoBean);
}