package cn.com.yuyang.pojo;

import java.util.Date;

public class Qingjiabiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.shenQingRen
     *
     * @mbg.generated
     */
    private Integer shenqingren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao. leiXing
     *
     * @mbg.generated
     */
    private String leixing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.qiShiShiJian
     *
     * @mbg.generated
     */
    private Date qishishijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.zhongZhiShiJian
     *
     * @mbg.generated
     */
    private Date zhongzhishijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.shenPiRen
     *
     * @mbg.generated
     */
    private Integer shenpiren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.chuLiZhuangTai
     *
     * @mbg.generated
     */
    private Integer chulizhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.shenQingShiJian
     *
     * @mbg.generated
     */
    private Date shenqingshijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.zhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qingjiabiao.qingJiaShiYou
     *
     * @mbg.generated
     */
    private String qingjiashiyou;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.id
     *
     * @return the value of qingjiabiao.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.id
     *
     * @param id the value for qingjiabiao.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.shenQingRen
     *
     * @return the value of qingjiabiao.shenQingRen
     *
     * @mbg.generated
     */
    public Integer getShenqingren() {
        return shenqingren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.shenQingRen
     *
     * @param shenqingren the value for qingjiabiao.shenQingRen
     *
     * @mbg.generated
     */
    public void setShenqingren(Integer shenqingren) {
        this.shenqingren = shenqingren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao. leiXing
     *
     * @return the value of qingjiabiao. leiXing
     *
     * @mbg.generated
     */
    public String getLeixing() {
        return leixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao. leiXing
     *
     * @param leixing the value for qingjiabiao. leiXing
     *
     * @mbg.generated
     */
    public void setLeixing(String leixing) {
        this.leixing = leixing == null ? null : leixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.qiShiShiJian
     *
     * @return the value of qingjiabiao.qiShiShiJian
     *
     * @mbg.generated
     */
    public Date getQishishijian() {
        return qishishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.qiShiShiJian
     *
     * @param qishishijian the value for qingjiabiao.qiShiShiJian
     *
     * @mbg.generated
     */
    public void setQishishijian(Date qishishijian) {
        this.qishishijian = qishishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.zhongZhiShiJian
     *
     * @return the value of qingjiabiao.zhongZhiShiJian
     *
     * @mbg.generated
     */
    public Date getZhongzhishijian() {
        return zhongzhishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.zhongZhiShiJian
     *
     * @param zhongzhishijian the value for qingjiabiao.zhongZhiShiJian
     *
     * @mbg.generated
     */
    public void setZhongzhishijian(Date zhongzhishijian) {
        this.zhongzhishijian = zhongzhishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.shenPiRen
     *
     * @return the value of qingjiabiao.shenPiRen
     *
     * @mbg.generated
     */
    public Integer getShenpiren() {
        return shenpiren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.shenPiRen
     *
     * @param shenpiren the value for qingjiabiao.shenPiRen
     *
     * @mbg.generated
     */
    public void setShenpiren(Integer shenpiren) {
        this.shenpiren = shenpiren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.chuLiZhuangTai
     *
     * @return the value of qingjiabiao.chuLiZhuangTai
     *
     * @mbg.generated
     */
    public Integer getChulizhuangtai() {
        return chulizhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.chuLiZhuangTai
     *
     * @param chulizhuangtai the value for qingjiabiao.chuLiZhuangTai
     *
     * @mbg.generated
     */
    public void setChulizhuangtai(Integer chulizhuangtai) {
        this.chulizhuangtai = chulizhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.shenQingShiJian
     *
     * @return the value of qingjiabiao.shenQingShiJian
     *
     * @mbg.generated
     */
    public Date getShenqingshijian() {
        return shenqingshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.shenQingShiJian
     *
     * @param shenqingshijian the value for qingjiabiao.shenQingShiJian
     *
     * @mbg.generated
     */
    public void setShenqingshijian(Date shenqingshijian) {
        this.shenqingshijian = shenqingshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.zhuangTai
     *
     * @return the value of qingjiabiao.zhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.zhuangTai
     *
     * @param zhuangtai the value for qingjiabiao.zhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qingjiabiao.qingJiaShiYou
     *
     * @return the value of qingjiabiao.qingJiaShiYou
     *
     * @mbg.generated
     */
    public String getQingjiashiyou() {
        return qingjiashiyou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qingjiabiao.qingJiaShiYou
     *
     * @param qingjiashiyou the value for qingjiabiao.qingJiaShiYou
     *
     * @mbg.generated
     */
    public void setQingjiashiyou(String qingjiashiyou) {
        this.qingjiashiyou = qingjiashiyou == null ? null : qingjiashiyou.trim();
    }
}