package cn.com.yuyang.pojo;

import java.util.Date;

public class Renyuandangan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.xingMing
     *
     * @mbg.generated
     */
    private String xingming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.ruZhiShiJian
     *
     * @mbg.generated
     */
    private Date ruzhishijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.heTongDaoQiShiJian
     *
     * @mbg.generated
     */
    private Date hetongdaoqishijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.xingBie
     *
     * @mbg.generated
     */
    private String xingbie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.shengRi
     *
     * @mbg.generated
     */
    private Date shengri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.jinJiLianXiDianHua
     *
     * @mbg.generated
     */
    private String jinjilianxidianhua;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.xianZhuZhi
     *
     * @mbg.generated
     */
    private String xianzhuzhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.xueLi
     *
     * @mbg.generated
     */
    private String xueli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.youXiang
     *
     * @mbg.generated
     */
    private String youxiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.biYeYuanXiao
     *
     * @mbg.generated
     */
    private String biyeyuanxiao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.zaiZhiZhuangTai
     *
     * @mbg.generated
     */
    private Integer zaizhizhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.minZu
     *
     * @mbg.generated
     */
    private String minzu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.jiGuan
     *
     * @mbg.generated
     */
    private String jiguan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.shenFenZheng
     *
     * @mbg.generated
     */
    private String shenfenzheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.zhengZhiMianMao
     *
     * @mbg.generated
     */
    private String zhengzhimianmao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.hunYin
     *
     * @mbg.generated
     */
    private String hunyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.nianLing
     *
     * @mbg.generated
     */
    private Integer nianling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.zhiWuId
     *
     * @mbg.generated
     */
    private Integer zhiwuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.buMenId
     *
     * @mbg.generated
     */
    private Integer bumenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.touXiang
     *
     * @mbg.generated
     */
    private String touxiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuandangan.beiZhu
     *
     * @mbg.generated
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.id
     *
     * @return the value of renyuandangan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.id
     *
     * @param id the value for renyuandangan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.xingMing
     *
     * @return the value of renyuandangan.xingMing
     *
     * @mbg.generated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.xingMing
     *
     * @param xingming the value for renyuandangan.xingMing
     *
     * @mbg.generated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.ruZhiShiJian
     *
     * @return the value of renyuandangan.ruZhiShiJian
     *
     * @mbg.generated
     */
    public Date getRuzhishijian() {
        return ruzhishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.ruZhiShiJian
     *
     * @param ruzhishijian the value for renyuandangan.ruZhiShiJian
     *
     * @mbg.generated
     */
    public void setRuzhishijian(Date ruzhishijian) {
        this.ruzhishijian = ruzhishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.heTongDaoQiShiJian
     *
     * @return the value of renyuandangan.heTongDaoQiShiJian
     *
     * @mbg.generated
     */
    public Date getHetongdaoqishijian() {
        return hetongdaoqishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.heTongDaoQiShiJian
     *
     * @param hetongdaoqishijian the value for renyuandangan.heTongDaoQiShiJian
     *
     * @mbg.generated
     */
    public void setHetongdaoqishijian(Date hetongdaoqishijian) {
        this.hetongdaoqishijian = hetongdaoqishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.xingBie
     *
     * @return the value of renyuandangan.xingBie
     *
     * @mbg.generated
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.xingBie
     *
     * @param xingbie the value for renyuandangan.xingBie
     *
     * @mbg.generated
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.shengRi
     *
     * @return the value of renyuandangan.shengRi
     *
     * @mbg.generated
     */
    public Date getShengri() {
        return shengri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.shengRi
     *
     * @param shengri the value for renyuandangan.shengRi
     *
     * @mbg.generated
     */
    public void setShengri(Date shengri) {
        this.shengri = shengri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.jinJiLianXiDianHua
     *
     * @return the value of renyuandangan.jinJiLianXiDianHua
     *
     * @mbg.generated
     */
    public String getJinjilianxidianhua() {
        return jinjilianxidianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.jinJiLianXiDianHua
     *
     * @param jinjilianxidianhua the value for renyuandangan.jinJiLianXiDianHua
     *
     * @mbg.generated
     */
    public void setJinjilianxidianhua(String jinjilianxidianhua) {
        this.jinjilianxidianhua = jinjilianxidianhua == null ? null : jinjilianxidianhua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.xianZhuZhi
     *
     * @return the value of renyuandangan.xianZhuZhi
     *
     * @mbg.generated
     */
    public String getXianzhuzhi() {
        return xianzhuzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.xianZhuZhi
     *
     * @param xianzhuzhi the value for renyuandangan.xianZhuZhi
     *
     * @mbg.generated
     */
    public void setXianzhuzhi(String xianzhuzhi) {
        this.xianzhuzhi = xianzhuzhi == null ? null : xianzhuzhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.xueLi
     *
     * @return the value of renyuandangan.xueLi
     *
     * @mbg.generated
     */
    public String getXueli() {
        return xueli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.xueLi
     *
     * @param xueli the value for renyuandangan.xueLi
     *
     * @mbg.generated
     */
    public void setXueli(String xueli) {
        this.xueli = xueli == null ? null : xueli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.youXiang
     *
     * @return the value of renyuandangan.youXiang
     *
     * @mbg.generated
     */
    public String getYouxiang() {
        return youxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.youXiang
     *
     * @param youxiang the value for renyuandangan.youXiang
     *
     * @mbg.generated
     */
    public void setYouxiang(String youxiang) {
        this.youxiang = youxiang == null ? null : youxiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.biYeYuanXiao
     *
     * @return the value of renyuandangan.biYeYuanXiao
     *
     * @mbg.generated
     */
    public String getBiyeyuanxiao() {
        return biyeyuanxiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.biYeYuanXiao
     *
     * @param biyeyuanxiao the value for renyuandangan.biYeYuanXiao
     *
     * @mbg.generated
     */
    public void setBiyeyuanxiao(String biyeyuanxiao) {
        this.biyeyuanxiao = biyeyuanxiao == null ? null : biyeyuanxiao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.zaiZhiZhuangTai
     *
     * @return the value of renyuandangan.zaiZhiZhuangTai
     *
     * @mbg.generated
     */
    public Integer getZaizhizhuangtai() {
        return zaizhizhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.zaiZhiZhuangTai
     *
     * @param zaizhizhuangtai the value for renyuandangan.zaiZhiZhuangTai
     *
     * @mbg.generated
     */
    public void setZaizhizhuangtai(Integer zaizhizhuangtai) {
        this.zaizhizhuangtai = zaizhizhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.minZu
     *
     * @return the value of renyuandangan.minZu
     *
     * @mbg.generated
     */
    public String getMinzu() {
        return minzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.minZu
     *
     * @param minzu the value for renyuandangan.minZu
     *
     * @mbg.generated
     */
    public void setMinzu(String minzu) {
        this.minzu = minzu == null ? null : minzu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.jiGuan
     *
     * @return the value of renyuandangan.jiGuan
     *
     * @mbg.generated
     */
    public String getJiguan() {
        return jiguan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.jiGuan
     *
     * @param jiguan the value for renyuandangan.jiGuan
     *
     * @mbg.generated
     */
    public void setJiguan(String jiguan) {
        this.jiguan = jiguan == null ? null : jiguan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.shenFenZheng
     *
     * @return the value of renyuandangan.shenFenZheng
     *
     * @mbg.generated
     */
    public String getShenfenzheng() {
        return shenfenzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.shenFenZheng
     *
     * @param shenfenzheng the value for renyuandangan.shenFenZheng
     *
     * @mbg.generated
     */
    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng == null ? null : shenfenzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.zhengZhiMianMao
     *
     * @return the value of renyuandangan.zhengZhiMianMao
     *
     * @mbg.generated
     */
    public String getZhengzhimianmao() {
        return zhengzhimianmao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.zhengZhiMianMao
     *
     * @param zhengzhimianmao the value for renyuandangan.zhengZhiMianMao
     *
     * @mbg.generated
     */
    public void setZhengzhimianmao(String zhengzhimianmao) {
        this.zhengzhimianmao = zhengzhimianmao == null ? null : zhengzhimianmao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.hunYin
     *
     * @return the value of renyuandangan.hunYin
     *
     * @mbg.generated
     */
    public String getHunyin() {
        return hunyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.hunYin
     *
     * @param hunyin the value for renyuandangan.hunYin
     *
     * @mbg.generated
     */
    public void setHunyin(String hunyin) {
        this.hunyin = hunyin == null ? null : hunyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.nianLing
     *
     * @return the value of renyuandangan.nianLing
     *
     * @mbg.generated
     */
    public Integer getNianling() {
        return nianling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.nianLing
     *
     * @param nianling the value for renyuandangan.nianLing
     *
     * @mbg.generated
     */
    public void setNianling(Integer nianling) {
        this.nianling = nianling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.zhiWuId
     *
     * @return the value of renyuandangan.zhiWuId
     *
     * @mbg.generated
     */
    public Integer getZhiwuid() {
        return zhiwuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.zhiWuId
     *
     * @param zhiwuid the value for renyuandangan.zhiWuId
     *
     * @mbg.generated
     */
    public void setZhiwuid(Integer zhiwuid) {
        this.zhiwuid = zhiwuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.buMenId
     *
     * @return the value of renyuandangan.buMenId
     *
     * @mbg.generated
     */
    public Integer getBumenid() {
        return bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.buMenId
     *
     * @param bumenid the value for renyuandangan.buMenId
     *
     * @mbg.generated
     */
    public void setBumenid(Integer bumenid) {
        this.bumenid = bumenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.touXiang
     *
     * @return the value of renyuandangan.touXiang
     *
     * @mbg.generated
     */
    public String getTouxiang() {
        return touxiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.touXiang
     *
     * @param touxiang the value for renyuandangan.touXiang
     *
     * @mbg.generated
     */
    public void setTouxiang(String touxiang) {
        this.touxiang = touxiang == null ? null : touxiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuandangan.beiZhu
     *
     * @return the value of renyuandangan.beiZhu
     *
     * @mbg.generated
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuandangan.beiZhu
     *
     * @param beizhu the value for renyuandangan.beiZhu
     *
     * @mbg.generated
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}