package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Renyuandangan;

public interface RenyuandanganMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    int insert(Renyuandangan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    int insertSelective(Renyuandangan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    Renyuandangan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Renyuandangan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Renyuandangan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renyuandangan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Renyuandangan record);
}