package cn.com.yuyang.pojo;

public class Rizhipinglun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rizhipinglun.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rizhipinglun.riZhiId
     *
     * @mbg.generated
     */
    private Integer rizhiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rizhipinglun.pingLunRen
     *
     * @mbg.generated
     */
    private Integer pinglunren;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rizhipinglun.id
     *
     * @return the value of rizhipinglun.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rizhipinglun.id
     *
     * @param id the value for rizhipinglun.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rizhipinglun.riZhiId
     *
     * @return the value of rizhipinglun.riZhiId
     *
     * @mbg.generated
     */
    public Integer getRizhiid() {
        return rizhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rizhipinglun.riZhiId
     *
     * @param rizhiid the value for rizhipinglun.riZhiId
     *
     * @mbg.generated
     */
    public void setRizhiid(Integer rizhiid) {
        this.rizhiid = rizhiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rizhipinglun.pingLunRen
     *
     * @return the value of rizhipinglun.pingLunRen
     *
     * @mbg.generated
     */
    public Integer getPinglunren() {
        return pinglunren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rizhipinglun.pingLunRen
     *
     * @param pinglunren the value for rizhipinglun.pingLunRen
     *
     * @mbg.generated
     */
    public void setPinglunren(Integer pinglunren) {
        this.pinglunren = pinglunren;
    }
}