package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Xinxi;

public interface XinxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    int insert(Xinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    int insertSelective(Xinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    Xinxi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Xinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinxi
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xinxi record);
}