package cn.com.yuyang.pojo;

import java.util.Date;

public class Xinxi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.faXinId
     *
     * @mbg.generated
     */
    private Integer faxinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.shouXinId
     *
     * @mbg.generated
     */
    private Integer shouxinid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.xinXiBiaoTi
     *
     * @mbg.generated
     */
    private String xinxibiaoti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.zhuangTai
     *
     * @mbg.generated
     */
    private Integer zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.xinXiShiJian
     *
     * @mbg.generated
     */
    private Date xinxishijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.fuJianDiZhi
     *
     * @mbg.generated
     */
    private String fujiandizhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.faSongZhuangTai
     *
     * @mbg.generated
     */
    private Integer fasongzhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.shouCangZhuangTai
     *
     * @mbg.generated
     */
    private Boolean shoucangzhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinxi.xinXiNeiRong
     *
     * @mbg.generated
     */
    private String xinxineirong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.id
     *
     * @return the value of xinxi.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.id
     *
     * @param id the value for xinxi.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.faXinId
     *
     * @return the value of xinxi.faXinId
     *
     * @mbg.generated
     */
    public Integer getFaxinid() {
        return faxinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.faXinId
     *
     * @param faxinid the value for xinxi.faXinId
     *
     * @mbg.generated
     */
    public void setFaxinid(Integer faxinid) {
        this.faxinid = faxinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.shouXinId
     *
     * @return the value of xinxi.shouXinId
     *
     * @mbg.generated
     */
    public Integer getShouxinid() {
        return shouxinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.shouXinId
     *
     * @param shouxinid the value for xinxi.shouXinId
     *
     * @mbg.generated
     */
    public void setShouxinid(Integer shouxinid) {
        this.shouxinid = shouxinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.xinXiBiaoTi
     *
     * @return the value of xinxi.xinXiBiaoTi
     *
     * @mbg.generated
     */
    public String getXinxibiaoti() {
        return xinxibiaoti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.xinXiBiaoTi
     *
     * @param xinxibiaoti the value for xinxi.xinXiBiaoTi
     *
     * @mbg.generated
     */
    public void setXinxibiaoti(String xinxibiaoti) {
        this.xinxibiaoti = xinxibiaoti == null ? null : xinxibiaoti.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.zhuangTai
     *
     * @return the value of xinxi.zhuangTai
     *
     * @mbg.generated
     */
    public Integer getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.zhuangTai
     *
     * @param zhuangtai the value for xinxi.zhuangTai
     *
     * @mbg.generated
     */
    public void setZhuangtai(Integer zhuangtai) {
        this.zhuangtai = zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.xinXiShiJian
     *
     * @return the value of xinxi.xinXiShiJian
     *
     * @mbg.generated
     */
    public Date getXinxishijian() {
        return xinxishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.xinXiShiJian
     *
     * @param xinxishijian the value for xinxi.xinXiShiJian
     *
     * @mbg.generated
     */
    public void setXinxishijian(Date xinxishijian) {
        this.xinxishijian = xinxishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.fuJianDiZhi
     *
     * @return the value of xinxi.fuJianDiZhi
     *
     * @mbg.generated
     */
    public String getFujiandizhi() {
        return fujiandizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.fuJianDiZhi
     *
     * @param fujiandizhi the value for xinxi.fuJianDiZhi
     *
     * @mbg.generated
     */
    public void setFujiandizhi(String fujiandizhi) {
        this.fujiandizhi = fujiandizhi == null ? null : fujiandizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.faSongZhuangTai
     *
     * @return the value of xinxi.faSongZhuangTai
     *
     * @mbg.generated
     */
    public Integer getFasongzhuangtai() {
        return fasongzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.faSongZhuangTai
     *
     * @param fasongzhuangtai the value for xinxi.faSongZhuangTai
     *
     * @mbg.generated
     */
    public void setFasongzhuangtai(Integer fasongzhuangtai) {
        this.fasongzhuangtai = fasongzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.shouCangZhuangTai
     *
     * @return the value of xinxi.shouCangZhuangTai
     *
     * @mbg.generated
     */
    public Boolean getShoucangzhuangtai() {
        return shoucangzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.shouCangZhuangTai
     *
     * @param shoucangzhuangtai the value for xinxi.shouCangZhuangTai
     *
     * @mbg.generated
     */
    public void setShoucangzhuangtai(Boolean shoucangzhuangtai) {
        this.shoucangzhuangtai = shoucangzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinxi.xinXiNeiRong
     *
     * @return the value of xinxi.xinXiNeiRong
     *
     * @mbg.generated
     */
    public String getXinxineirong() {
        return xinxineirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinxi.xinXiNeiRong
     *
     * @param xinxineirong the value for xinxi.xinXiNeiRong
     *
     * @mbg.generated
     */
    public void setXinxineirong(String xinxineirong) {
        this.xinxineirong = xinxineirong == null ? null : xinxineirong.trim();
    }
}