package cn.com.yuyang.pojo;

import java.util.Date;

public class Zhiwubiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.zhiWuMingCheng
     *
     * @mbg.generated
     */
    private String zhiwumingcheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.chaKanKaoQin
     *
     * @mbg.generated
     */
    private Boolean chakankaoqin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.qinJiaShenPi
     *
     * @mbg.generated
     */
    private Boolean qinjiashenpi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.buMenCaoZuo
     *
     * @mbg.generated
     */
    private Boolean bumencaozuo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.chaKanYuanGong
     *
     * @mbg.generated
     */
    private Boolean chakanyuangong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.caoZuoYuanGong
     *
     * @mbg.generated
     */
    private Boolean caozuoyuangong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao. faBuXiuGaiGongGao
     *
     * @mbg.generated
     */
    private Boolean fabuxiugaigonggao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.daiBanShiXiang
     *
     * @mbg.generated
     */
    private Boolean daibanshixiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.chuangJianShiJian
     *
     * @mbg.generated
     */
    private Date chuangjianshijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwubiao.zhiWuJianJie
     *
     * @mbg.generated
     */
    private String zhiwujianjie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.id
     *
     * @return the value of zhiwubiao.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.id
     *
     * @param id the value for zhiwubiao.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.zhiWuMingCheng
     *
     * @return the value of zhiwubiao.zhiWuMingCheng
     *
     * @mbg.generated
     */
    public String getZhiwumingcheng() {
        return zhiwumingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.zhiWuMingCheng
     *
     * @param zhiwumingcheng the value for zhiwubiao.zhiWuMingCheng
     *
     * @mbg.generated
     */
    public void setZhiwumingcheng(String zhiwumingcheng) {
        this.zhiwumingcheng = zhiwumingcheng == null ? null : zhiwumingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.chaKanKaoQin
     *
     * @return the value of zhiwubiao.chaKanKaoQin
     *
     * @mbg.generated
     */
    public Boolean getChakankaoqin() {
        return chakankaoqin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.chaKanKaoQin
     *
     * @param chakankaoqin the value for zhiwubiao.chaKanKaoQin
     *
     * @mbg.generated
     */
    public void setChakankaoqin(Boolean chakankaoqin) {
        this.chakankaoqin = chakankaoqin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.qinJiaShenPi
     *
     * @return the value of zhiwubiao.qinJiaShenPi
     *
     * @mbg.generated
     */
    public Boolean getQinjiashenpi() {
        return qinjiashenpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.qinJiaShenPi
     *
     * @param qinjiashenpi the value for zhiwubiao.qinJiaShenPi
     *
     * @mbg.generated
     */
    public void setQinjiashenpi(Boolean qinjiashenpi) {
        this.qinjiashenpi = qinjiashenpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.buMenCaoZuo
     *
     * @return the value of zhiwubiao.buMenCaoZuo
     *
     * @mbg.generated
     */
    public Boolean getBumencaozuo() {
        return bumencaozuo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.buMenCaoZuo
     *
     * @param bumencaozuo the value for zhiwubiao.buMenCaoZuo
     *
     * @mbg.generated
     */
    public void setBumencaozuo(Boolean bumencaozuo) {
        this.bumencaozuo = bumencaozuo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.chaKanYuanGong
     *
     * @return the value of zhiwubiao.chaKanYuanGong
     *
     * @mbg.generated
     */
    public Boolean getChakanyuangong() {
        return chakanyuangong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.chaKanYuanGong
     *
     * @param chakanyuangong the value for zhiwubiao.chaKanYuanGong
     *
     * @mbg.generated
     */
    public void setChakanyuangong(Boolean chakanyuangong) {
        this.chakanyuangong = chakanyuangong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.caoZuoYuanGong
     *
     * @return the value of zhiwubiao.caoZuoYuanGong
     *
     * @mbg.generated
     */
    public Boolean getCaozuoyuangong() {
        return caozuoyuangong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.caoZuoYuanGong
     *
     * @param caozuoyuangong the value for zhiwubiao.caoZuoYuanGong
     *
     * @mbg.generated
     */
    public void setCaozuoyuangong(Boolean caozuoyuangong) {
        this.caozuoyuangong = caozuoyuangong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao. faBuXiuGaiGongGao
     *
     * @return the value of zhiwubiao. faBuXiuGaiGongGao
     *
     * @mbg.generated
     */
    public Boolean getFabuxiugaigonggao() {
        return fabuxiugaigonggao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao. faBuXiuGaiGongGao
     *
     * @param fabuxiugaigonggao the value for zhiwubiao. faBuXiuGaiGongGao
     *
     * @mbg.generated
     */
    public void setFabuxiugaigonggao(Boolean fabuxiugaigonggao) {
        this.fabuxiugaigonggao = fabuxiugaigonggao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.daiBanShiXiang
     *
     * @return the value of zhiwubiao.daiBanShiXiang
     *
     * @mbg.generated
     */
    public Boolean getDaibanshixiang() {
        return daibanshixiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.daiBanShiXiang
     *
     * @param daibanshixiang the value for zhiwubiao.daiBanShiXiang
     *
     * @mbg.generated
     */
    public void setDaibanshixiang(Boolean daibanshixiang) {
        this.daibanshixiang = daibanshixiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.chuangJianShiJian
     *
     * @return the value of zhiwubiao.chuangJianShiJian
     *
     * @mbg.generated
     */
    public Date getChuangjianshijian() {
        return chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.chuangJianShiJian
     *
     * @param chuangjianshijian the value for zhiwubiao.chuangJianShiJian
     *
     * @mbg.generated
     */
    public void setChuangjianshijian(Date chuangjianshijian) {
        this.chuangjianshijian = chuangjianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwubiao.zhiWuJianJie
     *
     * @return the value of zhiwubiao.zhiWuJianJie
     *
     * @mbg.generated
     */
    public String getZhiwujianjie() {
        return zhiwujianjie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwubiao.zhiWuJianJie
     *
     * @param zhiwujianjie the value for zhiwubiao.zhiWuJianJie
     *
     * @mbg.generated
     */
    public void setZhiwujianjie(String zhiwujianjie) {
        this.zhiwujianjie = zhiwujianjie == null ? null : zhiwujianjie.trim();
    }
}