package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Zhiwubiao;

public interface ZhiwubiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    int insert(Zhiwubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    int insertSelective(Zhiwubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    Zhiwubiao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zhiwubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Zhiwubiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhiwubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Zhiwubiao record);
}