package cn.com.yuyang.pojo;

import cn.com.yuyang.pojo.Zuoxishijian;

public interface ZuoxishijianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuoxishijian
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuoxishijian
     *
     * @mbg.generated
     */
    int insert(Zuoxishijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuoxishijian
     *
     * @mbg.generated
     */
    int insertSelective(Zuoxishijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuoxishijian
     *
     * @mbg.generated
     */
    Zuoxishijian selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuoxishijian
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zuoxishijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuoxishijian
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Zuoxishijian record);
}