package cn.com.yuyang.pojo;

import java.util.Date;

public class Zuoxishijian {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuoxishijian.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuoxishijian.shangWuShangBan
     *
     * @mbg.generated
     */
    private Date shangwushangban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuoxishijian.xiaWuXiaBan
     *
     * @mbg.generated
     */
    private Date xiawuxiaban;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuoxishijian.id
     *
     * @return the value of zuoxishijian.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuoxishijian.id
     *
     * @param id the value for zuoxishijian.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuoxishijian.shangWuShangBan
     *
     * @return the value of zuoxishijian.shangWuShangBan
     *
     * @mbg.generated
     */
    public Date getShangwushangban() {
        return shangwushangban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuoxishijian.shangWuShangBan
     *
     * @param shangwushangban the value for zuoxishijian.shangWuShangBan
     *
     * @mbg.generated
     */
    public void setShangwushangban(Date shangwushangban) {
        this.shangwushangban = shangwushangban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuoxishijian.xiaWuXiaBan
     *
     * @return the value of zuoxishijian.xiaWuXiaBan
     *
     * @mbg.generated
     */
    public Date getXiawuxiaban() {
        return xiawuxiaban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuoxishijian.xiaWuXiaBan
     *
     * @param xiawuxiaban the value for zuoxishijian.xiaWuXiaBan
     *
     * @mbg.generated
     */
    public void setXiawuxiaban(Date xiawuxiaban) {
        this.xiawuxiaban = xiawuxiaban;
    }
}